"use client";
import { useEffect, useState } from "react";
import { CATS, CLASSES, NAMES, THEMES, type Theme } from "./data";
type Result = { id:number; name:string; className:string; cat:string; score:number; time:number; completedAt:string };
const fmt=(sec:number)=>`${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;
const fmtDate=(value:string)=>new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const PLAYER_PINS:Record<string,string>={"Савелий":"4564","Кирилл":"1332","Максим":"8861","Артём":"3273"};

export default function Home(){
  const [screen,setScreen]=useState<"start"|"pin"|"welcome"|"themes"|"quiz"|"result"|"rating">("start");
  const [name,setName]=useState(""),[className,setClassName]=useState(""),[cat,setCat]=useState("");
  const [theme,setTheme]=useState<Theme|null>(null),[index,setIndex]=useState(0),[score,setScore]=useState(0),[seconds,setSeconds]=useState(300);
  const [answered,setAnswered]=useState<number|null>(null),[results,setResults]=useState<Result[]>([]);
  const [pin,setPin]=useState(""),[pinError,setPinError]=useState(false);
  const [boardState,setBoardState]=useState<"idle"|"loading"|"ready"|"error">("idle");
  const [saveState,setSaveState]=useState<"idle"|"saving"|"saved"|"error">("idle");
  const selectedCat=CATS.find(c=>c.id===cat);
  async function loadLeaderboard(){setBoardState("loading");try{const response=await fetch("/api/leaderboard",{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {results:Result[]};setResults(data.results);setBoardState("ready")}catch{setBoardState("error")}}
  useEffect(()=>{if(screen==="rating")void loadLeaderboard()},[screen]);
  useEffect(()=>{if(screen!=="quiz"||answered!==null)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){finish(score,300);return 0}return s-1}),1000);return()=>clearInterval(t)},[screen,answered,score]);
  function begin(t:Theme){setTheme(t);setIndex(0);setScore(0);setSeconds(300);setAnswered(null);setScreen("quiz")}
  function openPin(){setPin("");setPinError(false);setScreen("pin")}
  function checkPin(e:React.FormEvent){e.preventDefault();if(pin===PLAYER_PINS[name]){setPin("");setPinError(false);setScreen("welcome")}else{setPin("");setPinError(true)}}
  function choose(i:number){if(answered!==null||!theme)return;setAnswered(i);const next=score+(i===theme.questions[index].correct?1:0);if(i===theme.questions[index].correct)setScore(next);setTimeout(()=>{if(index===4)finish(next,300-seconds);else{setIndex(v=>v+1);setAnswered(null)}},800)}
  function finish(finalScore:number,elapsed:number){if(screen!=="quiz")return;const safeTime=Math.max(1,Math.min(300,elapsed));setScore(finalScore);setSaveState("saving");setScreen("result");void fetch("/api/leaderboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,className,cat:cat||"inventor",score:finalScore,time:safeTime})}).then(response=>{if(!response.ok)throw new Error();setSaveState("saved")}).catch(()=>setSaveState("error"))}
  return <main className="app">
    <header className="topbar"><button className="brand" onClick={()=>setScreen("start")} aria-label="На главную"><img src="/gymnasium-40-logo.png" alt="Официальный знак гимназии № 40"/><span><b>КотоКласс</b><small>Гимназия № 40</small></span></button><button className="rating-btn" onClick={()=>setScreen("rating")}><span>🏆</span> Рейтинг</button></header>
    {screen==="start"&&<section className="start-grid"><div className="hero"><img src="/og.png" alt="Три кота в школьной мастерской"/><div className="hero-badge">5 вопросов · 5 минут · 9 тем</div></div><div className="setup-card"><p className="kicker">Готовы к умной перемене?</p><h1>Собери свою<br/><em>котокоманду!</em></h1><p className="lead">Выбери имя, класс и кота-помощника.</p>
      <fieldset><legend>1. Как тебя зовут?</legend><div className="choice-row">{NAMES.map(n=><button key={n} className={name===n?"selected":""} onClick={()=>setName(n)}>{n}</button>)}</div></fieldset>
      <fieldset><legend>2. Твой класс</legend><div className="choice-row two">{CLASSES.map(c=><button key={c} className={className===c?"selected":""} onClick={()=>setClassName(c)}>{c}</button>)}</div></fieldset>
      <fieldset><legend>3. Выбери кота</legend><div className="cat-row">{CATS.map(c=><button key={c.id} className={`cat-choice ${cat===c.id?"selected":""}`} onClick={()=>setCat(c.id)}><span>{c.emoji}</span><b>{c.name}</b><small>{c.role}</small></button>)}</div></fieldset>
      <button className="primary" disabled={!(name&&className&&cat)} onClick={openPin}>Начать игру <span>→</span></button></div></section>}
    {screen==="pin"&&<section className="center-screen"><form className="pin-card" onSubmit={checkPin}><button type="button" className="pin-back" onClick={()=>setScreen("start")}>← Назад</button><div className="pin-lock">🔐</div><p className="kicker">Секретный вход</p><h2>{name}, введи свой PIN</h2><p>Так мы узнаем, что это действительно ты.</p><label htmlFor="player-pin">PIN игрока</label><input id="player-pin" type="password" inputMode="numeric" pattern="[0-9]*" autoComplete="off" autoFocus value={pin} onChange={e=>{setPin(e.target.value.replace(/\D/g,"").slice(0,4));setPinError(false)}} aria-invalid={pinError} aria-describedby={pinError?"pin-error":undefined} placeholder="••••"/><div className="pin-dots" aria-hidden="true">{[0,1,2,3].map(i=><i key={i} className={i<pin.length?"filled":""}/>)}</div>{pinError&&<p id="pin-error" className="pin-error" role="alert">Не получилось войти. Проверь PIN и попробуй ещё раз.</p>}<button className="primary" type="submit" disabled={!pin}>Продолжить <span>→</span></button></form></section>}
    {screen==="welcome"&&<section className="center-screen"><div className="welcome-card"><div className="big-cat">{selectedCat?.emoji}</div><p className="kicker">Команда собрана!</p><h2>Привет, {name}!</h2><p>Я {selectedCat?.name}, твой кот-{selectedCat?.role}.<br/>{selectedCat?.hello}</p><button className="primary" onClick={()=>setScreen("themes")}>Выбрать тему <span>→</span></button></div></section>}
    {screen==="themes"&&<section className="content"><div className="section-heading"><div><p className="kicker">{name} · {className}</p><h2>Куда отправимся?</h2></div><p>В каждой теме — 5 вопросов.<br/>На миссию даётся 5 минут.</p></div><div className="theme-grid">{THEMES.map((t,i)=><button key={t.id} className="theme-card" style={{"--accent":t.color} as React.CSSProperties} onClick={()=>begin(t)}><span className="theme-no">0{i+1}</span><span className="theme-icon">{t.icon}</span><b>{t.title}</b><small>5 вопросов <i>→</i></small></button>)}</div></section>}
    {screen==="quiz"&&theme&&<section className="quiz-shell"><div className="quiz-top"><button onClick={()=>setScreen("themes")} className="back">← Темы</button><div className="quiz-title"><span style={{background:theme.color}}>{theme.icon}</span><b>{theme.title}</b></div><div className={`timer ${seconds<60?"danger":""}`}>⏱ {fmt(seconds)}</div></div><div className="progress"><i style={{width:`${((index+1)/5)*100}%`}}/></div><div className="question-card"><div className="question-meta"><span>Вопрос {index+1} из 5</span><span>{score} {score===1?"балл":"баллов"}</span></div><h2>{theme.questions[index].q}</h2><div className="answers">{theme.questions[index].a.map((a,i)=>{const cls=answered===null?"":i===theme.questions[index].correct?"correct":i===answered?"wrong":"dim";return <button key={a} className={cls} onClick={()=>choose(i)}><span>{String.fromCharCode(1040+i)}</span>{a}</button>})}</div><div className="cat-tip"><span>{selectedCat?.emoji}</span><p>{answered===null?"Не торопись — прочитай все варианты!":answered===theme.questions[index].correct?"Мур-р-р! Верно!":"Почти! Запомним правильный ответ."}</p></div></div></section>}
    {screen==="result"&&<section className="center-screen"><div className="result-card"><div className="confetti">★ ✦ ● ★</div><div className="trophy">🏆</div><p className="kicker">Миссия завершена</p><h2>{score===5?"Блестяще!":score>=3?"Отличная работа!":"Хорошая попытка!"}</h2><p>{name}, {selectedCat?.name} тобой гордится!</p><div className="result-stats"><div><b>{score}/5</b><small>верных ответов</small></div><div><b>{fmt(300-seconds)}</b><small>твоё время</small></div></div><p className={`save-note ${saveState}`}>{saveState==="saving"?"Сохраняем результат…":saveState==="saved"?"Результат появился в общем рейтинге!":saveState==="error"?"Не удалось сохранить результат. Проверь интернет.":""}</p><div className="result-actions"><button className="primary" onClick={()=>setScreen("themes")}>Другая тема</button><button className="secondary" onClick={()=>setScreen("rating")}>Смотреть рейтинг</button></div></div></section>}
    {screen==="rating"&&<section className="content rating-page"><div className="section-heading"><div><p className="kicker">Общий зал славы</p><h2>Рейтинг игроков</h2></div><div className="rating-actions"><button className="secondary compact" onClick={()=>void loadLeaderboard()}>↻ Обновить</button><button className="secondary compact" onClick={()=>setScreen("start")}>← На главную</button></div></div>{boardState==="loading"&&<p className="board-message">Собираем свежие результаты…</p>}{boardState==="error"&&<p className="board-message error">Не удалось загрузить рейтинг. Попробуй обновить.</p>}<div className="leaderboard"><div className="leader-head"><span>Место</span><span>Игрок</span><span>Счёт</span><span>Время</span><span>Когда</span></div>{results.length?results.map((r,i)=><div className={`leader-row ${i<3?`top top-${i+1}`:""}`} key={r.id}><span className="rank">{i<3?["🥇","🥈","🥉"][i]:i+1}</span><span className="player"><b>{r.name}</b><small>{r.className} · {CATS.find(c=>c.id===r.cat)?.name}</small></span><b className="points">{r.score}/5</b><span className="time">{fmt(r.time)}</span><span className="completed-at">{fmtDate(r.completedAt)}</span></div>):boardState==="ready"&&<div className="empty"><span>🐾</span><h3>Здесь пока тихо</h3><p>Сыграй первую игру — и твоё имя появится в общем рейтинге!</p><button className="primary" onClick={()=>setScreen("start")}>Начать игру</button></div>}</div><p className="local-note">Это общий рейтинг для всех игроков. При равном счёте выше тот, кто ответил быстрее. Показаны 50 лучших попыток.</p></section>}
  </main>
}
